### PR TITLE
Support phoenix_html v3.0.0

### PR DESCRIPTION
**Pull request by maennchen**

### CODE REVIEW

**Comment by maennchen** [comment]
@danhper Would you be able to review this? If the library is no longer maintained I would be able to provide some support for it.

**Review by Matsa59 — APPROVED** [review]
Let me check that on some projects to be sure of the impact then I'll merge it. 
Nice job !

**Comment by ruudk** [comment]
Thanks for merging this. Could you please tag a new release on https://hex.pm/packages/phoenix_active_link?

**Comment by Matsa59** [comment]
> Thanks for merging this. Could you please tag a new release on https://hex.pm/packages/phoenix_active_link?

Yes I didn't have rights and time to push new version :/ 

I'll do it this week !

**Comment by lukaszsamson** [comment]
Can we have a new release?

**Comment by Matsa59** [comment]
I totally forget to release the new version ... I'm really sorry, I was focus on company's project ...

This new version **DO NOT** ensure to work with heex. It **SHOULD** works but nothing was tested and/or validated.

**Pull request merged**
